### ISSUE TITLE
updatencep.py crashes in surface_reflectance_oct2016 and surface_reflectance_aug2016

### ISSUE THREAD

**Issue by daveoloughlin** [USGS-EROS/espa-surface-reflectance#70]
Argument list to program being debugged when it is started is "/tmp/ncep/slp.2015.nc /mnt/aux/REANALYSIS/RE_2015/REANALYSIS_2015078.hdf 78".
(gdb) backtrace
#0  0x00007ffff436eab4 in nc_inq (ncid=65536, ndimsp=0x7fffffffd520,
    nvarsp=0x7fffffffd524, nattsp=0x7fffffffd528, unlimdimidp=0x0)
    at dfile.c:1500
#1  0x0000000000400f3e in main (argc=<optimized out>, argv=0x7fffffffdd08)
    at ncep_reanalysis_surface_repackage.c:146

slp.2015.nc is opened and it can be viewed using the NetCDF (4.6) Tools UI. It appears that ncp->dispatch is an invalid address. 

I'm running version 1.9.0 of the product formatter. Also tried with surface_reflectance_aug2016 and product_formatter_v1.8.0.

**Comment by daveoloughlin** [comment]
P.S. Ran make check in netcdf4-4.4.1 and all tests passed

**Comment by daveoloughlin** [comment]
So, I rebuilt HDF4 and netCDF-4, using (from http://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html#build_hdf4) :

# Build and install HDF4
./configure --enable-shared --disable-netcdf --disable-fortran --prefix=$HDF4_PREFIX --with-jpeg=$JPEGLIB --with-zlib=$ZLIBLIB --with-szlib=$SZIPLIB --enable-static --enable-static-exec 
make check 
make install

# Build and install netCDF-4 with HDF4 access enabled CPPFLAGS="-I$HDF5_PREFIX/include -I$HDF4_PREFIX/include -I/usr/include/curl/" \
  LDFLAGS="-L$HDF5_PREFIX/lib -L$HDF4_PREFIX/lib -L/usr/lib" \
  ./configure --enable-hdf4 --enable-hdf4-file-tests --prefix=$NETCDF4_PREFIX --enable-shared --enable-static 
make check 
make install

Now  updatencep.py and the ncep_repackage program it calls complete without error. Thanks for the guidance from UCAR.
